# Build Stage
FROM node:20.11.1 as build

# ARG ARG_VITE_PROD_FIREBASE_API_KEY
# ARG ARG_VITE_PROD_FIREBASE_AUTH_DOMAIN
# ARG ARG_VITE_PROD_FIREBASE_PROJECT_ID
# ARG ARG_VITE_PROD_FIREBASE_STORAGE_BUCKET
# ARG ARG_VITE_PROD_FIREBASE_MESSAGING_SENDER_ID
# ARG ARG_VITE_PROD_FIREBASE_APP_ID
# ARG ARG_VITE_PROD_FIREBASE_MEASUREMENT_ID

# ARG ARG_VITE_PROD_POSTHOG_API_KEY
# ARG ARG_VITE_PROD_POSTHOG_API_HOST

# ARG ARG_VITE_PROD_API_HOST

# ENV VITE_PROD_FIREBASE_API_KEY=$ARG_VITE_PROD_FIREBASE_API_KEY
# ENV VITE_PROD_FIREBASE_AUTH_DOMAIN=$ARG_VITE_PROD_FIREBASE_AUTH_DOMAIN
# ENV VITE_PROD_FIREBASE_PROJECT_ID=$ARG_VITE_PROD_FIREBASE_PROJECT_ID
# ENV VITE_PROD_FIREBASE_STORAGE_BUCKET=$ARG_VITE_PROD_FIREBASE_STORAGE_BUCKET
# ENV VITE_PROD_FIREBASE_MESSAGING_SENDER_ID=$ARG_VITE_PROD_FIREBASE_MESSAGING_SENDER_ID
# ENV VITE_PROD_FIREBASE_APP_ID=$ARG_VITE_PROD_FIREBASE_APP_ID
# ENV VITE_PROD_FIREBASE_MEASUREMENT_ID=$ARG_VITE_PROD_FIREBASE_MEASUREMEN

# ENV VITE_PROD_API_HOST=$ARG_VITE_PROD_API_HOST

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install

COPY . .
RUN yarn build

# Production Stage
FROM nginx:1.25.4

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
